### ISSUE TITLE
GUI Commands

### ISSUE THREAD

**Issue by DrMoMo** [robscetury/gibson#2]
Hi,

I was a little bored and noticed the website did not have a keyboard mapping for the GUI.  Here is my attempt at it, hopefully this saves a little time and can help start the documentation pile.

http://momorabbithole.blogspot.com/2011/08/gibson-gui-commands.html

This weekend I'm going to try and address the configuration files and understand them.

**Comment by dklinedinst** [comment]
That's actually very complete.  Mind if I post it here and on the web site?  FYI, shift-z and shift-c move sideways (strafe) at ten times normal speed.  x is supposed to move back to the starting point, with the original rotation... but it gets off center because it moves relative to dummy_center_node, which itself moves, rather than relative to the true origin of the world.  q and e, on the other hand, do move relative to the world origin rather than relative to the center of the model as it currently exists on the screen.  Not sure if that should be changed.  g and b can also act odd based on previous transforms (movement) of the camera.

**Comment by DrMoMo** [comment]
No not at all, feel free to pull and use.  My goal is just to help the project along =D.
